### PR TITLE
Remove the "ballerina update" Command from the "Downloads" Page

### LINKED ISSUE #3278: Update the "ballerina-update" Command from the "Downloads" Page
**Description:**
Update the `ballerina-update` command from the "Downloads" page by removing the line below as per https://github.com/ballerina-platform/ballerina-dev-website/issues/3274.

**Under the Swan Lake section:**

`If your Update Tool is below version 0.8.14, use the ballerina update command. `

**Under the 1.2.x section:**

```
If you already have jBallerina version 1.2.0 or above installed, you can use the Ballerina Update Tool to directly update to 1.2.23. To do this, first, execute the command below to get the Update Tool updated to its latest version.

ballerina update
```

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by praneesha**
## Purpose
Remove the "ballerina update" command from the "Downloads" page.
> Fixes #3278 

## Check List

- [ ] **Page Addition**
  - [ ] Add `permalink` to pages
  - [ ] If contains empty folder(s), Add front-matter `redirect_to:`

- [ ] **Page Rename**
  - [ ] Add front-matter `redirect_from`
  - [ ] Add front-matter `redirect_to:` (If applicable)

### CODE REVIEW

**Comment by praneesha** [comment]
The changes done via this PR are as follows.

Screenshot 2021-12-22 at 17 19 34

Screenshot 2021-12-22 at 17 19 42

**Comment by praneesha** [comment]
Need to check if we can remove the `bal update` command totally (i.e., if it is sufficient to execute only the `bal dist pull` command) from both 1.2.x and Swan lake sections. @keizer619

**Comment by keizer619** [comment]
> Need to check if we can remove the `bal update` command totally (i.e., if it is sufficient to execute only the `bal dist pull` command) from both 1.2.x and Swan lake sections. @keizer619

Yes we can remove it as now `dist update` and `dist pull` update the tool itself

**Comment by praneesha** [comment]
Updated the Swan lake section of the Downloads page as shown below.

Screenshot 2022-01-04 at 15 31 53

**Review by keizer619 — APPROVED** [review]

**Pull request merged**
