### PR TITLE
[ Feature ] - Implemented the filter card

### LINKED ISSUE #8052: Implement filter card feature
## Description
Currently there are tabs displayed in following pages. Those tags should be clickable to filter and remove filter

https://ballerina.io/learn/integration-tutorials/
https://ballerina.io/learn/pre-built-integrations/
https://ballerina.io/learn/enterprise-integration-patterns/

Screenshot 2023-10-17 at 23 04 59

### PR DESCRIPTION
**Pull request by Pinaka-Pani-18**

### CODE REVIEW

**Comment by sm1990** [comment]
In `pre-built-integrations` the once you add the 3rd filter, the second one gets replaced.
In `enterprise-integration-patterns` and `Integration tutorials`, the 2nd filter is not working.
Remove the `package-lock.json` from the PR, since you haven't installed any new packages.

**Comment by Pinaka-Pani-18** [comment]
> In `pre-built-integrations` the once you add the 3rd filter, the second one gets replaced. In `enterprise-integration-patterns` and `Integration tutorials`, the 2nd filter is not working. Remove the `package-lock.json` from the PR, since you haven't installed any new packages.

In the 'pre-built-integrations' section, there was a duplicate issue. However, in the 'enterprise-integration-patterns' and 'Integration tutorials' sections, it is working fine. If any of the selected tags is present, it will display the card as shown in the video.

https://github.com/ballerina-platform/ballerina-dev-website/assets/102857774/51ba6852-a21b-4ea7-b1a0-bf8311566955

**Comment by sm1990** [comment]
@Pinaka-Pani-18 please check the following videos.

https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/84657000-574e-4626-be2f-72c7a7e48293


https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/185ed737-6bb8-4ace-b7bc-67f9323d7267


https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/c21ede83-8b28-4dfb-916a-b688b931b412

**Comment by Pinaka-Pani-18** [comment]
In the first two videos, it works like this: If any of the selected tags are present, it shows the card. 
Are you expecting it to filter only when both tags are present on the card to display it?

In the third video, there are duplicates, so it seems to be working like that. I will fix it.

**Comment by sm1990** [comment]
> In the first two videos, it works like this: If any of the selected tags are present, it shows the card. Are you expecting it to filter only when both tags are present on the card to display it?
Yes. When you add the 2nd filter, it should select cards that have both tags.

**Comment by Pinaka-Pani-18** [comment]
Hi @sm1990, I have made the necessary changes. Could you please review it now?

**Review by sm1990 — APPROVED** [review]

**Comment by sm1990** [comment]
@Pinaka-Pani-18 Thank you very much for your contribution. We are currently hosting a `Ballerina Hacktoberfest`. Since this issue is eligible for our event, please visit https://ballerina.io/hacktoberfest/#rules & submit the form. 😄

**Pull request merged**
