### PR TITLE
Add the Diagram to the Interoperability How-To Guide

### PR DESCRIPTION
**Pull request by praneesha**
## Purpose
This is to add the diagram to the Interoperability How-To Guide[1].

[1] https://ballerina.io/v1-2/learn/how-to-use-java-interoperability/
> Fixes #

## Check List

- [ ] **Page Addition**
  - [ ] Add `permalink` to pages
  - [ ] If contains empty folder(s), Add front-matter `redirect_to:`

- [ ] **Page Rename**
  - [ ] Add front-matter `redirect_from`
  - [ ] Add front-matter `redirect_to:` (If applicable)

### CODE REVIEW

**Comment by praneesha** [comment]
> Looks good. But the diagram is a bit too big. Can you please make it like 50% smaller?

@Samallama - Any idea how to make the diagram smaller?

**Comment by Samallama** [comment]
Can't we just resize the image and reupload it? I'm not sure how resizing works on markdown.

**Comment by Samallama** [comment]
Or we can use HTML instead of markdown just for this: drawing and resize it to whatever we need (width is in pixels)

**Comment by praneesha** [comment]
> Or we can use HTML instead of markdown just for this: `drawing` and resize it to whatever we need (width is in pixels)

Will try that. Thanks!

**Comment by praneesha** [comment]
> Can you please double-check? I don't see the image when the view the file?
> 
> @praneesha @Samallama

- If I add the path of the image as "src=/v1-2/learn/images/interoperability-diagram.png", the image is shown in the "View File" option but breaks in the website built locally.
- If I add the path of the image as "src=images/interoperability-diagram.png", the image will not show in the "View File" option but gets properly rendered in the website built locally.

Therefore, although, it's not shown in GItHub, I tested locally and it gets rendered as follows:

Screenshot 2020-03-25 at 13 11 08

@sameerajayasoma - Shall we merge the PR and see in "dev.website"?

**Pull request merged**
