### PR TITLE
copy code button added in Ballerina Action sample

### LINKED ISSUE #8001: Add a copy code button to Ballerina in Action samples
## Description
$subject 

image

### PR DESCRIPTION
**Pull request by s-vamshi**
> Fixes #8001 

This is how it looks
image

## Checklist

- [ ] **Page addition**
  - [ ] Add `permalink` to pages.

- [ ] **Page removal**
  - [ ] Remove entry from corresponding left nav YAML file.
  - [ ] Add `redirect_from` on the alternative page.
  - [ ] If no alternative page, add redirection on the `redirections.js ` file.

- [ ] **Page rename**
  - [ ] Add front-matter `redirect_from`.
  - [ ] Add front-matter `redirect_to:` (if applicable).

- [ ] **Page restrcuture**
  - [ ] Add `permalink` to pages.
  - [ ] Add front-matter `redirect_from`.
  - [ ] Add front-matter `redirect_to:` (if applicable).

### CODE REVIEW

**Comment by s-vamshi** [comment]
@sm1990 can you please review pr?

**Comment by sm1990** [comment]
@s-vamshi please add a copy button to the proto file in the grpc sample.
image

**Comment by s-vamshi** [comment]
@sm1990 can you please review now?
image

**Comment by sm1990** [comment]
@s-vamshi when copying the grpc sample, the both the Ballerina code and the proto code is shown as copied eventhough only one gets copied.
image

Also, in the copied text double quotes (`"`) are shown as `&quote;`
image
Try sending the raw code as a prop to `BalAction` component. That way you can get rid of the `htmlToCode` funtion as well.
Let me know if it works.

**Comment by s-vamshi** [comment]
> @s-vamshi when copying the grpc sample, the both the Ballerina code and the proto code is shown as copied eventhough only one gets copied.

Ya, It is because I am using same setCopied state for both code block.
Can I create a new state for proto code?

**Comment by s-vamshi** [comment]
@sm1990 can you please review now?
1.Removed htmltocode fun and used code props
2. Used another state for props copy

**Review by sm1990 — APPROVED** [review]

**Comment by s-vamshi** [comment]
@sm1990 I have submitted the form for previous PR as part of Hacktoberfest, should I submit the form another response with this PR link?

**Comment by sm1990** [comment]
> @sm1990 I have submitted the form for previous PR as part of Hacktoberfest, should I submit the form another response with this PR link?

Yes please. Thank you again for your your contribution :smile:

**Pull request merged**
