### PR TITLE
Add syntax highlighting to nested code blocks#6656

### LINKED ISSUE #6656: Add syntax highlighting to nested code blocks

### PR DESCRIPTION
**Pull request by ashutuptiwari**
## Checklist

- [ ] **Page addition**
  - [ ] Add `permalink` to pages.

- [ ] **Page removal**
  - [ ] Remove entry from corresponding left nav YAML file.
  - [ ] Add `redirect_from` on the alternative page.
  - [ ] If no alternative page, add redirection on the `redirections.js ` file.

- [ ] **Page rename**
  - [ ] Add front-matter `redirect_from`.
  - [ ] Add front-matter `redirect_to:` (if applicable).

- [ ] **Page restrcuture**
  - [ ] Add `permalink` to pages.
  - [ ] Add front-matter `redirect_from`.
  - [ ] Add front-matter `redirect_to:` (if applicable).

### CODE REVIEW

**Comment by ashutuptiwari** [comment]
@sm1990 please review this PR and suggest changes that are required(if any). Issue #6656

**Comment by sm1990** [comment]
> @sm1990 please review this PR and suggest changes that are required(if any). Issue #6656

@ashutuptiwari Thank you for your contribution. However, this is not the expected solution. Please refer to the comment(https://github.com/ballerina-platform/ballerina-dev-website/pull/8009#issuecomment-1754732787) I have added explaining the issue and the expected solution in detail.

**Review by sm1990 — CHANGES_REQUESTED** [review]
Please address the issues mentioned in the previous comment.

**Comment by ashutuptiwari** [comment]
@sm1990 so the changes need to be made in the file  https://github.com/ballerina-platform/ballerina-dev-website/blob/master/utils/highlighter.js rather than the .md?

**Comment by sm1990** [comment]
> @sm1990 so the changes need to be made in the file https://github.com/ballerina-platform/ballerina-dev-website/blob/master/utils/highlighter.js rather than the .md?
Yes

**Pull request closed without merging**
