### PR TITLE
Added copy code button to sample code in website pages #8028

### LINKED ISSUE #8028: Add copy code button to sample code in website pages
## Description

$subject in learn pages. 

e.g. https://ballerina.io/learn/get-started/

image

### PR DESCRIPTION
**Pull request by nooras**
## Checklist

- [x] **Page restrcuture**
  - [x] Added Copy Code in `./components/common/main-content/MainContent.js`

### Note: In all possible pages wherever MainContent.js file is used to convert Markdown page, Copy Code Icon is added.

**1. Full Page of Get Started**
screencapture-localhost-3000-learn-get-started-2023-10-22-21_03_51

**2. Full Page of Integration - Open Api Tool Page**
screencapture-localhost-3000-learn-openapi-tool-2023-10-22-21_11_18

**3. Copied one of the code block then its showing copied checkbox only to respective code block. Example 1**
image

**4. Copied one of the code block then its showing copied checkbox only to respective code block. Example 2**
image

**5. Checked icon change to Copy icon after 3 seconds**
image

Let me know in case of any changes. Please review the changes @anupama-pathirage, @ThisaruGuruge, @sm1990

### CODE REVIEW

**Comment by sm1990** [comment]
@nooras Thank you for your contribution.

Could you please do the following improvements.

- When copying terminal command like the one below, the output also get copied. Users should be able to copy only the command. You can filter it by checking for lines starting with `$`. image

- There is too much space between the copy button and the code in code blocks where syntax highlighting has been applied (hello world code) compared to the ones without syntax highlighting (terminal commands). image

**Comment by nooras** [comment]
> @nooras Thank you for your contribution.
> 
> Could you please do the following improvements.
> 
> * When copying terminal command like the one below, the output also get copied. Users should be able to copy only the command. You can filter it by checking for lines starting with `$`. image
> * There is too much space between the copy button and the code in code blocks where syntax highlighting has been applied (hello world code) compared to the ones without syntax highlighting (terminal commands). image

Hi @sm1990 

I have made changes for point 1.
In 2nd point, I have removed padding bottom.
but here in this file global.css there is margin-top: 20px due to which there is gap between Code and copy icon.
If i made change there then it may affect in some other places. Shall i remove margin-top from global.css ??
image

**Comment by sm1990** [comment]
> @nooras Thank you for your contribution.
> 
> Could you please do the following improvements.
> 
> * When copying terminal command like the one below, the output also get copied. Users should be able to copy only the command. You can filter it by checking for lines starting with `$`. image
> * There is too much space between the copy button and the code in code blocks where syntax highlighting has been applied (hello world code) compared to the ones without syntax highlighting (terminal commands). image

@nooras that margin-top was added to maintain the space between the text and the code. Seems like its now getting maintained by a `div` you have added.
image
You can go ahead and remove that `margin-top:20px`

**Comment by nooras** [comment]
> > @nooras Thank you for your contribution.
> > Could you please do the following improvements.
> > 
> > * When copying terminal command like the one below, the output also get copied. Users should be able to copy only the command. You can filter it by checking for lines starting with `$`. image
> > * There is too much space between the copy button and the code in code blocks where syntax highlighting has been applied (hello world code) compared to the ones without syntax highlighting (terminal commands). image
> 
> @nooras that margin-top was added to maintain the space between the text and the code. Seems like its now getting maintained by a `div` you have added. image You can go ahead and remove that `margin-top:20px`

No no, @sm1990 that margin top is for space between grey div like box and white space between text description!!

And that margin-top between copy checkbox & code is coming from that .css file.

**Comment by sm1990** [comment]
> > > @nooras Thank you for your contribution.
> > > Could you please do the following improvements.
> > > 
> > > * When copying terminal command like the one below, the output also get copied. Users should be able to copy only the command. You can filter it by checking for lines starting with `$`. image
> > > * There is too much space between the copy button and the code in code blocks where syntax highlighting has been applied (hello world code) compared to the ones without syntax highlighting (terminal commands). image
> > 
> > 
> > @nooras that margin-top was added to maintain the space between the text and the code. Seems like its now getting maintained by a `div` you have added. image You can go ahead and remove that `margin-top:20px`
> 
> No no, @sm1990 that margin top is for space between grey div like box and white space between text description!!
> 
> And that margin-top between copy checkbox & code is coming from that .css file.

Yes. I think you can remove the one coming from the css file. Before you added the copy button, that `margin-top` help creating a space between the text and the code. Now we don't need it.

**Comment by nooras** [comment]
Hi @sm1990,

Have made changes. Kindly please review the changes and let me know incase of any changes.

Thanks

**Review by sm1990 — APPROVED** [review]

**Comment by sm1990** [comment]
@nooras Thank you for your contribution. We are currently hosting a `Ballerina Hacktoberfest`. Since this issue is eligible for our event, please visit https://ballerina.io/hacktoberfest/#rules & submit the form. 😄

**Pull request merged**
